services:
  game:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UNITY_SERIAL: ${UNITY_SERIAL}
        UNITY_EMAIL: ${UNITY_EMAIL}
        UNITY_PASSWORD: ${UNITY_PASSWORD}
    ports:
      - "8080:80"
    restart: unless-stopped
